"""visit_logs

Revision ID: 50db8e0e9156
Revises: f44f5f692cde
Create Date: 2026-09-30 10:40:24.442692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '50db8e0e9156'
down_revision: Union[str, None] = 'f44f5f692cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_logs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('vdate', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('visitor_key', sa.String(length=16), nullable=False),
    sa.Column('listing_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vdate_hour', 'visit_logs', ['vdate', 'hour'], unique=False)
    op.create_index('idx_vdate_listing', 'visit_logs', ['vdate', 'listing_id'], unique=False)
    op.create_index('idx_vdate_visitor', 'visit_logs', ['vdate', 'visitor_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vdate_visitor', table_name='visit_logs')
    op.drop_index('idx_vdate_listing', table_name='visit_logs')
    op.drop_index('idx_vdate_hour', table_name='visit_logs')
    op.drop_table('visit_logs')
    # ### end Alembic commands ###
