"""init 4 tables

Revision ID: f44f5f692cde
Revises: 
Create Date: 2026-09-29 18:09:51.733163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'f44f5f692cde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=127), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('listings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('landlord_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('village', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('rent', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('deposit_type', sa.String(length=16), nullable=False),
    sa.Column('layout', sa.String(length=16), nullable=False),
    sa.Column('area', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('floor_total', sa.Integer(), nullable=False),
    sa.Column('has_elevator', sa.Boolean(), nullable=False),
    sa.Column('facing', sa.String(length=50), nullable=True),
    sa.Column('private_bathroom', sa.Boolean(), nullable=False),
    sa.Column('water_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('electric_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('available_date', sa.Date(), nullable=False),
    sa.Column('metro_line', sa.String(length=16), nullable=True),
    sa.Column('metro_station', sa.String(length=32), nullable=True),
    sa.Column('walk_minutes', sa.Integer(), nullable=True),
    sa.Column('surroundings', sa.String(length=200), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('wechat', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_city_metro', 'listings', ['city', 'status', 'metro_station'], unique=False)
    op.create_index('idx_city_status_rent', 'listings', ['city', 'status', 'rent'], unique=False)
    op.create_index('idx_city_village', 'listings', ['city', 'status', 'village'], unique=False)
    op.create_index('idx_landlord', 'listings', ['landlord_id', 'status'], unique=False)
    op.create_table('reports',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('listing_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status', 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_status', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_landlord', table_name='listings')
    op.drop_index('idx_city_village', table_name='listings')
    op.drop_index('idx_city_status_rent', table_name='listings')
    op.drop_index('idx_city_metro', table_name='listings')
    op.drop_table('listings')
    op.drop_table('users')
    op.drop_table('cities')
    # ### end Alembic commands ###
